# Generated by Django 4.1.13 on 2024-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.TextField(default='', null=True),
        ),
    ]
