# Generated by Django 4.1.13 on 2024-05-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(default='', null=True),
        ),
    ]
