# Generated by Django 4.1.13 on 2024-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_model', '0002_rename_title_book_name_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
