# Generated by Django 4.1.13 on 2024-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(default='', max_length=225, null=True),
        ),
    ]
